[package]

name = "schannel"
license = "MIT"
version = "0.0.1"
description = "Schannel bindings for rust, allowing SSL/TLS (e.g. https) without openssl, including hyper integration"
authors = [ "Steffen Butzer <steffen.butzer@outlook.com>" ]
documentation = "http://steffengy.github.io/rust-schannel/doc/schannel/"
repository = "https://github.com/steffengy/rust-schannel"
readme = "README.md"
keywords = ["windows", "schannel", "win32", "ssl", "tls", "https", "hyper"]

[lib]
name = "schannel"
path = "src/lib.rs"
test = false
bench = false

[dependencies]
rustc-serialize = "0.3"
hyper = { version = "*", optional = true, default-features = false }
log = "0.3"

[dev-dependencies]
env_logger = "*"

[dependencies.winapi]
git="https://github.com/retep998/winapi-rs.git"

[dependencies.secur32-sys]
git="https://github.com/retep998/winapi-rs.git"

[dependencies.crypt32-sys]
git="https://github.com/retep998/winapi-rs.git"

[features]
default = ["hyper"]
