[package]

name = "schannel"
license = "MIT"
version = "0.0.1"
description = "Schannel bindings for rust, allowing https without openssl, with hyper integration"
authors = [ "steffenb198@aol.com" ]
readme = "README.md"
keywords = ["windows", "schannel", "win32", "ssl", "https", "hyper"]

[lib]
name = "schannel"
path = "src/lib.rs"
test = false
bench = false

[dependencies]
rustc-serialize = "0.3"
hyper = { version = "*", optional = true, default-features = false }
log = "0.3"

[dev-dependencies]
env_logger = "*"

[dependencies.winapi]
git="https://github.com/retep998/winapi-rs.git"

[dependencies.secur32-sys]
git="https://github.com/retep998/winapi-rs.git"

[dependencies.crypt32-sys]
git="https://github.com/retep998/winapi-rs.git"

[features]
default = ["hyper"]

